### ISSUE TITLE
cURL GET request to api.api gives me 401 error

### ISSUE THREAD

**Issue by rmawani** [mevdschee/php-api-auth#10]
Hi, 

First off, thank you so much for the great auth and crud APIs. You have really saved me (and I'm sure, many others) a lot of time by making them available publicly!

Anyway, I've managed to get the everything up and running in my environment to a point where I can use PostMan and/or a Browser to register a user, authenticate this user and then use the resulting CSRF token to perform GET/POST/PUT requests as advertised.

My issue arises when I try to send a cURL (GET) request from the project directory on my Production Web Server to the API to retrieve a list of Users from the database. The same URL entered into the browser retrieves the data as expected but not when it is accessed via a cURL request.

My code is as follows:

```
$Url = 'http://example/api/Users?transform=1&csrf='.$_SESSION['csrf'];

$ch = curl_init();

$timeout = 5;
curl_setopt($ch, CURLOPT_URL, $Url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

$Users = curl_exec($ch);

if ($Users === FALSE) {
    die("Curl failed: " . curL_error($ch));
}

$ch_info = curl_getinfo($ch);

var_dump($Url, $Users, $Users['Users'], $ch_info);

curl_close($ch);
```

In the above code, var_dump shows me the following:

1.  $Url -> http://example/api/Users?transform=1&csrf=1234567890123456789
2. $Users -> string (0) ""
3. $Users['Users'] -> string (0) ""
4. $ch_info -> ["url"] ->http://example/api/Users?transform=1&csrf=1234567890123456789, ["http_code"]=> int(401) amongst other things...

I worked around this issue by performing the GET using client-side AJAX/JQuery which tells me that I have a Cookies-related issue as the CSRF I receive from the User Auth request will create a client-side Cookie and I need one that sit on the Server for internal Auth. 

I hope the above makes sense to you and you can give me some insight into what I've done wrong and how to go about fixing it?

Thanks in advance for your help!

**Comment by mevdschee** [comment]
Thank you for your kind words! Please take a look at #7, especially COOKIEJAR and COOKIEFILE. I think this is where your problem lies.

**Comment by rmawani** [comment]
Thanks for your super quick reply!

I took a look at [#7](https://github.com/mevdschee/php-api-auth/issues/7) and modified my code accordingly by calling cURL twice, once to authenticate the user and then once more to process the GET request.

Still no joy...

Here is my updated code:

```
$Url = 'http://example.com/api/';
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $Url);
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=admin&password=admin"); 
curl_setopt ($ch, CURLOPT_COOKIEJAR, $tmp_file); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$output = json_decode(curl_exec($ch), ture);

if ($output === FALSE) {
    die("Curl failed: " . curL_error($ch));
}

$Url = 'http://example.com/api/Users?transform=1&csrf='.$output['csrf'];
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $Url);
curl_setopt ($ch, CURLOPT_COOKIEFILE, $tmp_file);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$Users = curl_exec($ch);

if ($Users === FALSE) {
    die("Curl failed: " . curL_error($ch));
}

$ch_info = curl_getinfo($ch);

var_dump($Url, $Users, $Users['Users'], $ch_info);

curl_close($ch);

unlink($tmp_file);
```

This var_dump looks identical to the one output by my last iteration of code...

**Comment by mevdschee** [comment]
Can try to you add cookiejar and cookiefile to both calls? Does the file exist? Does it get filled?

**Comment by rmawani** [comment]
hmmm... It looks like the file does not get created as a var_dump($tmp_file, file_exists($tmp_file)) results in NULL and false... Could this be some sort of a directory permissions issue?

**Comment by rmawani** [comment]
Finally fixed it! Thanks so much for your help!

Turns out it was a bit of a permissions issue as I was not creating the file in a location that could be written to. In my case, I decided to create the cookie in the Web Server's root tmp folder.

Thanks again!

**Comment by mevdschee** [comment]
You are welcome!

**Comment by rmawani** [comment]
Very good point... Thanks for the advice! Works like a charm now!

Thanks again!!
