### ISSUE TITLE
Auth returns 401 when using cURL

### ISSUE THREAD

**Issue by ablears** [mevdschee/php-api-auth#11]
First, thanks so much for the time you've put into this framework.

I've read through the other issues about cURL, and have similar issues despite checking things like the cookie files. I am using the 'Simple username + password' method.

The first POST, to get the CSRF, works fine. I get the numeric CSRF as expected, and a cookie is created in the temp folder.

I do another send, this time with the CSRF attached as a GET parameter. This returns a 401.

My code is this:

    //create credentials array
    $data=array(
	'username'=>'admin',
	'password'=>'admin'
    );

    //encode the credentials 
    $data=json_encode($data);

    //create a temporary file
    $tmpFname = tempnam("/tmp/api/","COOKIE");

    //the URL to send to
    $url='https://example.co.uk/api/v2/api.php/';

    //POST credentials to the auth (/), storing the session in the COOKIEJAR
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_COOKIEJAR, $tmpFname);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');	
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $credentialsCall=curl_exec($ch);
    curl_close($ch);

    error_log(print_R('Response from credentials post: '.$credentialsCall,TRUE)); //eg 715552116

    if(is_numeric($credentialsCall)){
	//the response to the first call should be the csrf, so...
	//request again, this time passing the csrf as a GET parameter
	$csrf=$credentialsCall;
	$url='https://example.co.uk/api/v2/api.php/my_table?csrf='.$csrf;

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_COOKIEFILE, $tmpFname);
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	$apiCall=curl_exec($ch);
	curl_close($ch);

	error_log(print_R('Response from second request: '.$apiCall,TRUE)); //eg '' (empty)

    }

    unlink($tmpFname);

In api.php, I have

    require 'auth.php'; // from the PHP-API-AUTH project, see: https://github.com/mevdschee/php-api-auth

    $auth = new PHP_API_AUTH(array(
 	'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); }
     ));
     if ($auth->executeCommand()) exit(0);
     if (empty($_SESSION['user']) || $_GET['csrf']!=$_SESSION['csrf']) {
 	error_log('Unauthorized');
 	error_log(print_R($_SESSION['user'],TRUE)); //eg '' (empty)
 	error_log(print_R($_GET['csrf'],TRUE)); //eg 715552116
 	error_log(print_R($_SESSION['csrf'],TRUE)); //eg 257581241
	header('HTTP/1.0 401 Unauthorized');
	exit(0);
     }

The issues seems to be:
1/ $_SESSION['user'] is empty. 
2/ $_GET['csrf'] doesn't match $_SESSION['csrf'].

The temp file looks like this:

    #HttpOnly_.example.co.uk	TRUE	/	FALSE	1517880843	__cfduid	d290745ee12a3cd1a25ac9ee62fb3c5091486344843`

Any ideas would be much appreciated!

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. I'll try to help you as good as I can. Try replacing:

    $tmpFname = tempnam("/tmp/api/","COOKIE");

with:

    $tmpFname = tempnam(sys_get_temp_dir(),"COOKIE");

I'm guessing this could help, because I wasn't able to reproduce your problem (yet). See also:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_auth.php

This is a working example. I hope this helps!

**Comment by ablears** [comment]
Thanks for the help! Unfortunately using `$tmpFname = tempnam(sys_get_temp_dir(),"COOKIE");` didn't change anything, and using your working example results in the same issue. 

Trying this code on another server works (unfortunately not the one I need it on) so I guess this is a server config issue, something to do with session management or PHP 7.1... not sure. Even just using Postman doesn't work.

**Comment by mevdschee** [comment]
I can help you debug the issue. Send me a private email to discuss.

**Comment by mevdschee** [comment]
I can help you debug the issue. Send me a private email to discuss.

**Comment by ablears** [comment]
OK, thanks.
