### ISSUE TITLE
Token+Session auth trouble...

### ISSUE THREAD

**Issue by rmawani** [mevdschee/php-api-auth#12]
Hi!

Thanks again for the great api's!

I've been successfully using Form+Session auth and have had very little trouble (at least since the last time you pointed me in the right direction). Yesterday, I decided to try out Token+Session auth to see if it might suit some of my auth needs better.

I tried using the following block of code:

```
$auth = new PHP_API_AUTH(array(
 	'secret'=>'mysecrethere',
 	'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); }
));
if ($auth->executeCommand()) exit(0);
```

...and expectedly receive a valid JWT indicating "user": true.

Where I am currently stuck, is what to do from here. Do I need to post the JWT back to the API in order to get a CSRF for use in the CRUD transactions or, do I use the JWT itself in place of the CSRF in the CRUD transactions? I've tried both but seem to be getting a null CSRF in the first instance and a 401-Unauthorized in the second instance.

Please help see what I'm doing wrong here...

**Comment by mevdschee** [comment]
The JWT is issued by your authentication server, let's say: auth.yourservice.tld

The session + CSRF are still needed to run your api on:  api.yourservice.tld

To transfer trust from auth.yourservice.tld to api.yourservice.tld the JWT is used.

On auth.yourservice.tld you only run the php-api-auth project, not php-crud-api.

On auth.yourservice.tld you use in the auth configuration both secret and authenticator.

On api.yourservice.tld you use in the auth configuration only the (same) secret.

**Comment by rmawani** [comment]
Thanks a bunch for clearing that up for me! Works perfectly!

**Comment by mevdschee** [comment]
I'm glad it did. Enjoy the software!
