### ISSUE TITLE
Example of server config

### ISSUE THREAD

**Issue by younesouhbi** [mevdschee/php-api-auth#13]
Hi there,
First thanks for the awesome accelerator.
Please note that I am new to PHP, my last time using it goes back more than 15 years...
I'm trying to use the username + password authentication, it doesn't matter what I do, I get 200 Ok on the first post request to api.php on '/' but any subsequent request ends in 401. Is there an example of usage available that I can follow? I've only seen the client usage example but none for the server. Is there also a documentation explaining the different settings?
Thank you and sorry for the basic questions

**Comment by mevdschee** [comment]
There are a few authentication examples here:

https://github.com/mevdschee/php-crud-api/tree/master/examples

They have "auth" in the name.

>I've only seen the client usage example but none for the server.

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_auth.php

Like that one?

>Is there also a documentation explaining the different settings?

The files contain some comments that may be useful.

**Comment by younesouhbi** [comment]
Thank you for the examples. I'll go over them but I still fail to understand what PHP_API_AUTH attempts to do.
I failed to mention that I'm using Aurelia with the Aurelia-auth plugin which sends the token with each request after a successful login.
What I don't understand is how PHP_API_AUTH uses this token to verify that the user is in fact authenticated:

```
if (empty($_SESSION['user']) || !$auth->hasValidCsrfToken()) {
	header('HTTP/1.0 401 Unauthorized');
	exit(0);
}
```
hasValidCsrfToken returns false if $_SESSION['csrf'] isn't set and it's never set if you use an authenticator as well as a secret. In this case (authenticator with a secret) causes $no_session to be true which causes the generation of a token without ever setting $_SESSION['csrf'] while the authenticator supposedly sets $_SESSION['user'] which seems to contradict the fact that the session isn't used as this is a REST api.

Sorry but I'm lost :)
The library seems to be covering multiple scenarios and I seem to be mixing them. Any clarifications would be most welcome.

**Comment by younesouhbi** [comment]
I narrowed the problem down to PHP creating a new session on refresh which leads to the token sent with the header having a different value than the one that gets generated again and again which then leads to 401 unauthorized.

**Comment by mevdschee** [comment]
It is typically due to the following lines missing:

    curl_setopt($ch, CURLOPT_COOKIEJAR, $cookiejar);
    curl_setopt($ch, CURLOPT_COOKIEFILE, $cookiejar);

I hope that helps.

**Comment by mevdschee** [comment]
Closed due to inactivity

**Comment by carlo-fontanos** [comment]
Same here, I'm lost on the usage of **PHP_API_AUTH**. Do you have an example  script that demonstrates an actual login with logout? 

Like a form where users can log in then it compares the credentials against the database via `api.php`, and sets the session, and uses the session on the condition on weather to show the logout button or not, and then clears the session on-click of logout button?
