### ISSUE TITLE
Username/password authentication

### ISSUE THREAD

**Issue by reubenwalkerau** [mevdschee/php-api-auth#15]
Hi Maurits

Thank you for your sharing your work, it's excellent code and very helpful.

Sorry for asking a simple question, I may be missing something obvious. I'm seeing a token returned for any username/password pair, even null. 

How can I make this authenticate against known credentials?

```
$ curl http://localhost:8888/api.php
$ curl http://localhost:8888/api.php --data "username=admin&password=admin"
"3463927620177487360"
$ curl http://localhost:8888/api.php --data "username=foo&password=bar"
"6364633731514325019"
$ curl http://localhost:8888/api.php --data "username=&password="
"1322945882537392955"
$
```

**Comment by mevdschee** [comment]
Please investigate this example to see how it is supposed to work:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_auth.php

I hope that gets you any further.

**Comment by mevdschee** [comment]
Or alternatively look at this example:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_bash_auth.sh

Showing the following commands:

    #!/bin/bash
    
    # initialize empty cookie store
    cp /dev/null cookies.txt
    
    # login and store cookies in 'cookies.txt' AND retrieve the value of the XSRF token
    TOKEN=`curl 'http://localhost:8888/blog.php/' --data "username=admin&password=admin" --cookie-jar cookies.txt --silent`

    # strip the double quotes from the variable (JSON decode)
    TOKEN=${TOKEN//\"/}

    # set the XSRF token as the 'X-XSRF-Token' header AND send the cookies to the server
    curl 'http://localhost:8888/blog.php/posts?include=categories,tags,comments&filter=id,eq,1' --header "X-XSRF-Token: $TOKEN" --cookie cookies.txt
    
    # clean up
    rm cookies.txt

This should help you, right?

**Comment by reubenwalkerau** [comment]
Thank you that is helpful. My question was really more along the lines of #4 and #5, how/where to implement a username/password validation?

**Comment by mevdschee** [comment]
Please read these tickets:

https://github.com/mevdschee/php-crud-api/issues?q=is%3Aissue+authenticator+is%3Aclosed

Especially the following comment:

https://github.com/mevdschee/php-crud-api/issues/117#issuecomment-256551221

I hope that helps!

**Comment by reubenwalkerau** [comment]
I think this comment is what I was looking for:
https://github.com/mevdschee/php-crud-api/issues/117#issuecomment-256795657

**Comment by reubenwalkerau** [comment]
Its working as expected now. Thank you for your great work and for your assistance.

**Comment by mevdschee** [comment]
I'm glad it works now, enjoy the software!

**Comment by sujathavts** [comment]
@reubenwalkerau how did you implement the username/password check?

**Comment by mjza** [comment]
> Please investigate this example to see how it is supposed to work:
> 
> https://github.com/mevdschee/php-crud-api/blob/master/examples/client_auth.php
> 
> I hope that gets you any further.

the link does not exist anymore!

**Comment by mevdschee** [comment]
>the link does not exist anymore!

It has been moved to:

https://github.com/mevdschee/php-crud-api/tree/master/examples/clients/auth.php
