### ISSUE TITLE
App key?

### ISSUE THREAD

**Issue by reubenwalkerau** [mevdschee/php-api-auth#20]
Is it possible to setup a permanent app key such that a particular app can access the api without first fetching a csrf every time?

Possibly a way to make a csrf persistent rather than time out?

**Comment by mevdschee** [comment]
>Possibly a way to make a csrf persistent rather than time out?

No, it would defeat the purpose of a CSRF. What you can do if you understand the security implications is: turn it off by commenting out the security check.

**Comment by reubenwalkerau** [comment]
Ok thank you I'll take a look at that. 

I'm interested in authorising a mobile app with an app key and secret. I know this is very commonly done but not sure how it's implemented.

**Comment by reubenwalkerau** [comment]
From looking at auth.php I understand that the token expires after 30 minutes.

68         if (!$ttl) {
69             $ttl = 30;

What is the best practice for csrf tokens?
Should my client app save and re-use the token, then check whether it has expired and fetch a new one, or would it be better not to save the token and just fetch a new one before every REST operation?

**Comment by mevdschee** [comment]
>the token expires after 30 minutes.

That is 30 seconds

>would it be better not to save the token and just fetch a new one before every REST operation?

The login token is not the same as the csrf token. You should save the csrf token and re-use it during the session.

**Comment by mevdschee** [comment]
This functionality is completely overhauled in php-crud-api v2. Please try it out.
