### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by mnicic** [mevdschee/php-api-auth#21]
Am I wrong, or this can't be used with Basic Auth?

**Comment by mevdschee** [comment]
Basic auth is currently not supported.

**Comment by mycaravam** [comment]
Put this on top of api.php. It enables a crude basicAuth, just for tests. I use this in my projects til implementing "better" Auth methods.
```
// This handles the Basic Auth from PHP
function require_auth() {
  $AUTH_USER = 'username';
  $AUTH_PASS = 'password';
  header('Cache-Control: no-cache, must-revalidate, max-age=0');
  $has_supplied_credentials = !(empty($_SERVER['PHP_AUTH_USER']) && empty($_SERVER['PHP_AUTH_PW']));
  $is_not_authenticated = (
    !$has_supplied_credentials ||
    $_SERVER['PHP_AUTH_USER'] != $AUTH_USER ||
    $_SERVER['PHP_AUTH_PW']   != $AUTH_PASS
  );
  if ($is_not_authenticated) {
    header('HTTP/1.1 401 Authorization Required');
    header('WWW-Authenticate: Basic realm="Access denied"');
    exit;
  }
}
require_auth();
```

**Comment by mbnoimi** [comment]
@mycaravam Why you don't make Pull request?

**Comment by mevdschee** [comment]
Basic auth over SSL is not such a bad approach. Hard-coding the username and password on the other hand is something I would not recommend. Also not using "password_hash" seems like a security issue to me. See: https://secure.php.net/manual/en/function.password-hash.php

**Comment by mycaravam** [comment]
@mbnoimi because it's not part of this project. You can attach this snippet to any php-file. Maybe it even was a mistake to post this, someone might think you could use this in production or do it anyway.
For me it's just part of a work-around and this especially is simplified code to 'fit' in one file as an example.
My own app uses a user-table and gets the credentials from there.

**Comment by mevdschee** [comment]
Basic auth is now supported. It is added as a middleware in php-crud-api v2.
