### ISSUE TITLE
Using Auth only for PUT/POST/DELETE requests

### ISSUE THREAD

**Issue by ezetojo** [mevdschee/php-api-auth#22]
Hey @mevdschee . First of all thanks for this awesome tool. I'm just wondering if there's any way to use the auth only for PUT/POST/DELETE requests to prevent inserts or updates of unwanted data and leave the GET requests publics (without auth).

**Comment by mevdschee** [comment]
Thank you for reaching out and for your compliments! 

I guess you can add a condition for the HTTP method.

Something like:

    if (empty($_SESSION['user']) || !$auth->hasValidCsrfToken()) {

replaced by:

    if ($_SERVER['REQUEST_METHOD']!='GET' && (empty($_SESSION['user']) || !$auth->hasValidCsrfToken())) {

I hope that helps.

**Comment by ezetojo** [comment]
That's a great solution.
Now i can't make any request that isn't GET. Cool.
Next step... I got the token from login_token.
But now i'm trying to test it in postman and i can't make it work...
I tryed using X-XSRF-TOKEN and XSRF-TOKEN header and the token but always returns 401.
I can't figure it out.
Sorry and thanks in advance!

**Comment by mevdschee** [comment]
Please check #10 and if that does not help you open a new issue. Thank you!

**Comment by ezetojo** [comment]
Thanks @mevdschee ! I'll keep trying.
