### ISSUE TITLE
How can I combine Auth0 and php-api-auth?

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-api-auth#23]
I am currently implementing an admin part of my website and going to use Auth0 for authorization and splitting permissions purposes. I have deployed php-api and have a simple Auth0 app that can just authorize me into an admin panel. After login, a user obtains a token and a corresponding role, I just need somehow to verify the token and to split functionality in the API. 

Is there a proven path to combine Auth0 and php-api?

Many thanks

**Comment by mevdschee** [comment]
There is not yet support, nor does anything prevent it from being implemented. See: https://oauth.net/code/

**Comment by mevdschee** [comment]
In this is now fully supported in php-crud-api v2 (even without php-api-auth). Please try it out!

There is an example here:

https://github.com/mevdschee/php-crud-api/tree/master/examples/clients/auth0
