### ISSUE TITLE
Trouble getting simple AUTH to work

### ISSUE THREAD

**Issue by hisbluness** [mevdschee/php-api-auth#25]
Hey sir,

I've been playing around with your regular API and it is great fun and very helpful. I want to add the AUTH plugin but have trouble doing so.

I've added the respective lines in the api.php (uncommented the parts near the end):

`require 'auth.php'; $auth = new PHP_API_AUTH(array( 'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); } )); if ($auth->executeCommand()) exit(0); if (empty($_SESSION['user']) || !$auth->hasValidCsrfToken()) { header('HTTP/1.0 401 Unauthorized'); exit(0); }`

I've also added the auth.php and the login/logout.html pages. When using login.html I receive a token result in the body and the header and also a cookie.

Once I perform /api.php?csrf=MYTOKEN I receive the swagger output.
Trying to access /api.php?csrf=MYTOKEN/ or /api.php?csrf=MYTOKEN/TableName I receive a 401 unauthorized.

Accessing the table without the auth plugin works perfectly fine. I cant figure out what I am doing wrong. I have taken everything from the source here and just adjusted my database configuration. When sending my request for the table I can see in Fiddler that the cookie is sent, too. It is also the same cookie I have received during the login procedure.

Any hints? My .php is very limited and I have failed to turn something up in google.
Thanks a bunch for any help.
chris

**Comment by hisbluness** [comment]
I just noticed that I get a token regardless of the user/pass I enter in the login.html. I'd appreciate any hints/tips.

**Comment by mevdschee** [comment]
I think you are confused by the three different tokens: CSRF, Authentication and Session

You should send an username and password and then receive a session token (in the cookie). You also receive a CSRF token that you have to actively send along in every next request. You may also do this using a header (like Angular2 and React do this).

If you want to use a JWT token to authenticate you can do so, but I would only use it in a SSO scenario.

**Comment by hisbluness** [comment]
Thanks for the prompt response. You are right, maybe I'm confusing things. Maybe it helps to explain what I try to do and maybe there is a problem with my idea of how it should/could work.

What I want to accomplish:
I'm writing something in .NET/C# where it would be nice to store a bit of information in an online database. I tried your version without AUTH to check if it would be possible/sufficient and it is. Accessing data via /api.php/Tablename works as described. To protect the interface from unwanted access I need some sort of simple authentication to prevent that anyone with the URL can do operations via REST.

While I was writing a response to you with all the technical information and what didn't work I just miraculously discovered I am an idiot and that I was the problem:

After receiving the token I always tried /api.php?csrf=TOKEN/Tablename because your example shows it like that and I didn't know any better. Obviously, when comparing this to like **any** other site on this planet, the URI should be /api.php/Tablename?csrf=TOKEN. 

And guess what, that seems to work. Sorry about that I think I am fine now. Will continue testing the next days.

**Comment by mevdschee** [comment]
Thank you for reporting this. You write:

> After receiving the token I always tried /api.php?csrf=TOKEN/Tablename because your example shows it like that and I didn't know any better.

That sounds like a bug in the documentation/example, where did you find that? I would love to fix that.

**Comment by hisbluness** [comment]
Sure thing.
On the AUTH page https://github.com/mevdschee/php-api-auth within the readme.md (or directly on the page) this bold sentence lead me astray:

> Simple
> username + password
> On API server
> login.html is loaded
> sends username + password via POST to "api.php/"
> api.php (POST on "/" gets hijacked by auth.php) is loaded
> sends back csrf token + http-only session cookie
> **call API as: api.php?csrf=[csrf token] (session cookie is sent automatically)**

Probably only relevant for people inexperienced in regards to web technology. Thanks for your response and help. So far it is looking good. Great work on this project!

**Comment by mevdschee** [comment]
Thank you, I understand how this can be confusing.
