### ISSUE TITLE
Authentification Issue

### ISSUE THREAD

**Issue by CharifAbdeslam** [mevdschee/php-api-auth#28]
First of all hello and thank you for this work, i am getting issue working with the authentication
Here is my code
```
$.ajax({
  url:"./src/api.php",
  method:"post",
  data:{
    username:"admin",
    password:"admin"
  },
  success:function(res){
    console.log(res)
    $.ajax({
      url:"./src/api.php?csrf="+[res]+"/costumers_info",
      method:"get",
      success:function(data){
        console.log(data)
      }
    })
  }
})
```

I was able to get the token wish for some weird reason no matter what i submit on the first post request is "N1991573504" , but in the second request where i need to fetch the data i am still getting error  401 Unauthorized
this is how the header of my request look like 

`http://localhost/src/api.php?csrf=%22N649003008%22/costumers_info `
```
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection:keep-alive
Cookie:PHPSESSID=n12nqa0m1gfgeamem270arrnl4; XSRF-TOKEN=N649003008
Host:localhost
Referer:http://localhost/apitest.html
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
X-Requested-With:XMLHttpRequest
```

any idea on how to solve the issue 
Thanks

**Comment by mevdschee** [comment]
Thank you for your kind words. You need to change the order of the csrf and the path as such:

    url:"./src/api.php/costumers_info?csrf="+[res],

I hope this helps.

**Comment by CharifAbdeslam** [comment]
Thanks Man i will try it and let you know

**Comment by CharifAbdeslam** [comment]
Hello mevdschee  , finally it working  when i switched to` url:"./src/api.php/costumers_info?csrf="+[res],`
again Thank you a lot

**Comment by mevdschee** [comment]
Great, enjoy the software!
