### ISSUE TITLE
Check token

### ISSUE THREAD

**Issue by geeekcode** [mevdschee/php-api-auth#3]
If the token that is generated is incorrect when we press the 'OK' button after the login page we can enter the api file, that is incorrect right? How can I change that?
Is supposed the token be always the same? And how I can define a timeout for the token? 
Sorry for the multiples questions and good work!

**Comment by mevdschee** [comment]
> that is incorrect right?

Uncomment one of both methods in api.php

> Is supposed the token be always the same?

No, it is not

> And how I can define a timeout for the token? 

It is defined in the 'auth.php' file as 'ttl' and can be specified as an option in 'api.php' when loading the auth object:

```
    require 'auth.php';
    $auth = new PHP_API_AUTH(array(
        'secret'=>'someVeryLongPassPhrase',
        'ttl'=>30
    ));
    $auth->executeCommand();
    if (empty($_SESSION['user'])) exit(header('HTTP/1.1 403 Access denied'));
```

Does this help?

**Comment by geeekcode** [comment]
Yes thank you! And how I can request token to url? I think that part is missing me... Every url after the login must have the token on url right?

**Comment by mevdschee** [comment]
No, after "logging in" with a token you get a (http-only) session cookie.

**Comment by mevdschee** [comment]
I have tried to clarify the process in the readme.
