### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-api-auth#30]
Hi,
I implemented AUTH with authentication server (token+user+pass).
If a hacker want to view (through sniffing for example) the data that I'm sending via POST, he could know the user and password and could use the api. It's true?

If yes, for make a REAL security, should I use ALWAYS https? If I don't use https is easy to hack? 

And my other question is about logout.html, when I should use the logout? I could use login_token.php and get different tokens every time I want to get or post data, and never use logout. It's wrong?

Thanks.

**Comment by mevdschee** [comment]
First of all: Security is a hard topic, please read a lot about it.

>should I use ALWAYS https

Yes

>If I don't use https is easy to hack?

Yes

>when I should use the logout?

When you have finished your session.

>and get different tokens every time I want to get or post data

The idea is that you are creating a session with a session cookie.

NB: It sounds like you are new to this. Please ask for professional advice if you are publishing real data.

**Comment by raz0r007** [comment]
Ok but, the **csrf** generated after login, has an expiration? Or it never expires?

**Comment by mevdschee** [comment]
It expires when the session expires.
