### ISSUE TITLE
Is there a way to combine it with social logins?  

### ISSUE THREAD

**Issue by WJanbaz** [mevdschee/php-api-auth#31]
Hi, thanks for this great job. 

I am thinking of using php-crud-api with php-api-auth combining a social login (Gmail, FB ...) developed using angular (ex: https://github.com/sabyasachibiswal/angular5-social-login) . Basically, my idea is user connects with FB or Gmail before being able to call any REST API through php-crud-api. Do you have any documentation or examples somewhere?

**Comment by mevdschee** [comment]
Hooking it up to a service like auth0 would probably be useful. See: https://auth0.com

If you succeed, please post the code for others to use. :-)

**Comment by mevdschee** [comment]
In this is now fully supported in php-crud-api v2 (even without php-api-auth) using Auth0. Please try it out!

There is an example here:

https://github.com/mevdschee/php-crud-api/tree/master/examples/clients/auth0
