### ISSUE TITLE
SESSION

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-api-auth#33]
Hi
I'm having this error :

Notice: Undefined variable: _SESSION in /home/php-crud-api-master/auth.php on line 196
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mjg0MTk4OTIsImV4cCI6MTUyODQxOTkyMn0.eOV6tbWX-I8Yoo1qrdDQyeO4cboSTp9yLYMf6USrQmk"/>

Why? I'm trying to implement login with token.
Regards

**Comment by mevdschee** [comment]
Hi.. Do you know why there is a "/>" at the end of the error message?

**Comment by raz0r007** [comment]
I think because in login_token.php i found this line at the end:
?>/>

But that's not the problem, I tested deleting it and the error continues.

**Comment by raz0r007** [comment]
This is the steps that I followed for activate login with token:

- In api.php (downloaded from php-crud-api) i uncomment the first part:

require 'auth.php'; // from the PHP-API-AUTH project, see: https://github.com/mevdschee/php-api-auth

// uncomment the lines below for token+session based authentication (see "login_token.html" + "login_token.php"):

$auth = new PHP_API_AUTH(array(
'secret'=>'test',
));
if ($auth->executeCommand()) exit(0);
if (empty($_SESSION['user']) || !$auth->hasValidCsrfToken()) {
header('HTTP/1.0 401 Unauthorized');
exit(0);
}


- In login_token.php i setted the same secret and a new user/pass.

- I copied login_token.php and auth.php from php-api-auth to php-crud-api

End.

**Comment by raz0r007** [comment]
I discovered why is that error.
The user/pass for login is admin admin, if you try to login with a different user/pass, login_token.php returns that notice instead of an invalid token.

Can you test it?
2 months ago I remember that I tested it and it worked well, the login_tokens returned me an invalid token instead of that error.

I saw that php-crud-api was updated. Maybe it's a bug?
Can you test it?

**Comment by raz0r007** [comment]
Ok I solved the problem, this is my final login_token.php



```
<?php
require 'auth.php';

$auth = new PHP_API_AUTH(array(
	'secret'=>'someVeryLongPassPhraseChangeMe',
	'authenticator'=>function($user,$pass){ if ($user=='admin' && $pass=='admin') $_SESSION['user']=$user; }
));
@$auth->executeCommand();
?>
```



I added "@" for avoid the Notice. 
Programmers like me that we making a program in c++, is very annoying a Notice in the response. So, evaluate improve that :). I know that maybe I can solve it by configuration, but.. whatever...

**Comment by mevdschee** [comment]
Thank you. I'm glad you solved your problem. Thank you for sharing. I agree that the notice should be avoided and not hidden with the @. I'll see whether or not I can reproduce this and fix it if I can. Kind regards, Maurits
