### ISSUE TITLE
HTTP Error 401 unauthorized cache-control

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-api-auth#36]
Hi,
I i've an auth problem with the API.
I don't know if the problem is the api, the server, or mine.

I'm programming an App for iOS and Android.
In iOS i'm connecting with the api and everything works fine (including the auth).
But in Andoid, with the same code that i'm using for iOS, i've auth problems.

I'm logging in and it works ok (i'm getting the correct csrf). But when I try to select registers from a table, this is the response:

```
ResponseCode: 401
ResponseHeader: HTTP/1.1 401 Unauthorized \n Cache-Control: no-store
ResponseData:
```

Is a rare behavior because the code and the server is the same.
And i'm integrating ok the api because in iOS works perfect.

Maybe should I use a different header for send request? this is my header:

```
    vector<string> header;
    header.emplace_back("User-Agent: MyApp/1.0");
    header.emplace_back("Content-Type: application/x-www-form-urlencoded");
    httpRequest->setHeaders(header);
```

Help plz.

**Comment by mevdschee** [comment]
~~Can you use Charles or Fiddler (debugging proxies) and do a recording of the messages going back and forth and post them here? Maybe I can help you then.~~

You are probably not supporting the session cookies required.

**Comment by raz0r007** [comment]
> You are probably not supporting the session cookies required.

And how can I solve that?

**Comment by mevdschee** [comment]
I don't know. Probably by using a CookieStore, see:

https://developer.android.com/reference/java/net/CookieStore

**Comment by raz0r007** [comment]
After debugging on both platforms, I detected a difference in the Headers.
In iOS the Headers that I'm trying to use for get information has a **Set-Cookie** parameter, that contains the php-session. 

In Android, with the same request, doesn't exist **Set-Cookie** parameter in the headers.

Maybe your link is useful but anyway I don't know how to solve this problem... :(

**Comment by raz0r007** [comment]
I found the problem. I share here for (maybe) help to someone else.
The problem is with the Cookies in Http.

When I log in to the API, the http response header contains a new Cookie value:
`Set-Cookie: value`

I should to use that ‘value’ always that I would want to use GET requests.
For all GET requests, in the header, I need add `Cookie: value`
And now everything works fine.

**Comment by mevdschee** [comment]
I'm glad that you found the problem. Enjoy the software!
