### ISSUE TITLE
with axios or fetch

### ISSUE THREAD

**Issue by simonplm** [mevdschee/php-api-auth#39]
is it possible to use jwtauth with just axios or fetch? thanks

**Comment by mevdschee** [comment]
I'm not sure, but I guess you can. Is there a problem you are running into?

**Comment by simonplm** [comment]
I got it working. But i have to edit the auth.php. instead of redirecting, I just echo the access token to get it from the response.data and just put it in the GET request header. thanks

**Comment by mevdschee** [comment]
Is there an example that you can share with the community?
