### ISSUE TITLE
how to setup middleware to work with auth0

### ISSUE THREAD

**Issue by paitoncamp** [mevdschee/php-api-auth#41]
How to setup a config parameters for the middleware to work with auth0? I already set a parameter "middleware:jwtAuth", but have no idea where/how to set the middleware to accept valid audience/authorized_iss from auth0 ( in other words, how php-crud-api knows that a token is a valid token from auth0) without using php-api-auth

**Comment by mevdschee** [comment]
You don't need this project when setting up Auth0 based auth for php-crud-api, for more information read: 

https://github.com/mevdschee/php-crud-api#configure-and-test-jwt-authentication-with-auth0

>have no idea where/how to set the middleware to accept valid audience/authorized_iss

You should set the config parameters: jwtAuth.secret, jwtAuth.audiences and jwtAuth.issuers

**Comment by paitoncamp** [comment]
do you have a complete example of config parameters using jwtAuth?

**Comment by mevdschee** [comment]
>do you have a complete example of config parameters using jwtAuth?

No, nothing more than the walk-through that I already linked.

**Comment by paitoncamp** [comment]
I got this error 

> <br/><b>Warning</b>: openssl_verify(): suppliedkeyparamcannotbecoercedintoapublickeyin<b>C: \xampp7\htdocs\php-crud-api\api.php</b>online<b>7551</b><br/>{
  "code": 1012,
  "message": "Authentication failed for 'JWT'"
}

Is there I missing here?

**Comment by mevdschee** [comment]
> suppliedkeyparamcannotbecoercedintoapublickey

This means you didn't properly specify the public key.. please post your config so that people can help you. Also, please use the issues of php-crud-api. This project is irrelevant for your use case.
