### ISSUE TITLE
check username/password against database

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-api-auth#5]
csrf token is still generated when no username/password is provided or if username/password is wrong. Is this an error or should be be checked by developer? 

UPDATE:
i was able to check if the fields were blank using javascript, How can i check if the username/password is wrong? Should i be using the server method in your example? I think i am using simple right now.

**Comment by ubergeekzone** [comment]
figured this one out, thanks!

**Comment by reubenwalkerau** [comment]
@ubergeekzone, how did you implement the username/password check?

**Comment by sujathavts** [comment]
@ubergeekzone, how did you implement the username/password check?
