### ISSUE TITLE
Send csrf on Create/Post

### ISSUE THREAD

**Issue by fvdias** [mevdschee/php-api-auth#7]
I've enabled simple user/pass authentication and it works fine when I try to post records using get. 

I use curl to post username and password as defined on api.php and get the csrf token in return I then send the csrf on the url as api.php/table/?csrf=tokenvalue and it returns the json with the records as expected. 

The problem is when I try to create a record also using curl. I first post the username and password, get the proper token, but when I send the csrf as one of the post fields it does not work. I've also tried using in the curl url as /?csrf=tokenvalue but no luck. 

I hope I explained the issue well enough and I would really appreciate your help perhaps with a simples post create example. 

Thanks.

**Comment by mevdschee** [comment]
Thank you for reaching out. You should still send the csrf token as a get
parameter, even on post or put.

**Comment by fvdias** [comment]
I've tried doing that using curl to send the csrf in the url as site.com/api.php/users?csrf=tokenvalue

Still it does nothing. The same code works and creates a record if I remove uthentication

**Comment by fvdias** [comment]
I've also tested with POSTMAN (Chrome extension) sending the same post that works but passing the csrf token on the url and it doesn't work. It works fine on Get.

**Comment by fvdias** [comment]
My code that does not work:

`<?php

$ch = curl_init();                    // initiate curl
$url = "http://www.mysite.com.br/api/api.php"; // where you want to post data
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_POST, true);  // tell curl you want to post something
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=admin&password=admin"); // define what you want to post
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // return the output in string format
$output = curl_exec ($ch); // execute

curl_close ($ch); // close curl handle

$ch2 = curl_init();                    // initiate curl

$url2 = "http://www.mysite.com.br/api/api.php/users?csrf=".$output; // where you want to post data
curl_setopt($ch2, CURLOPT_URL,$url2);
curl_setopt($ch2, CURLOPT_POST, true);  // tell curl you want to post something
curl_setopt($ch2, CURLOPT_POSTFIELDS, "username=John&email=some@emailoop.com"); // define what you want to post
curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true); // return the output in string format
$output2 = curl_exec ($ch2); // execute


curl_close ($ch2); // close curl handle

var_dump($output2); // show output


?>`

**Comment by mevdschee** [comment]
The problem is that you receive a session cookie that you should store in the cookie jar

    // Tells curl to store received cookies in the temporary file
    curl_setopt ($ch, CURLOPT_COOKIEJAR, $tmp_fname);

In the second request you should send the session id using a cookie:

    // Tells curl to send received cookies from the temporary file
    curl_setopt ($ch2, CURLOPT_COOKIEFILE, $tmp_fname);

For more information see: https://mydevthoughts.wordpress.com/2011/05/10/using-php-curl-with-session-cookies/

**Comment by fvdias** [comment]
Thanks for the reply. I'm not sending the username and password on the second request. My table has username and email fields.

So this 
curl_setopt ($ch, CURLOPT_COOKIEJAR, $tmp_fname);

should be on my first request and $tmp_fname = my $output, correct?

thanks again

**Comment by fvdias** [comment]
I checked the link you suggested and changed my code as follows, but still no luck. The cookie is generated correctly and the URL is appending the token correctly. Thanks again for your help.

<pre>
<?php
$tmp_fname = tempnam("./","COOKIE");

$ch = curl_init();                    // initiate curl
$url = "http://www.foneparking.com.br/api/api.php"; // where you want to post data
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_POST, true);  // tell curl you want to post something
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=admin&password=admin"); // define what you want to post
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // return the output in string format
$output = curl_exec ($ch); // execute

curl_setopt ($ch, CURLOPT_COOKIEJAR, $tmp_fname);

echo $output; // show output
echo $tmp_fname; // show output


$url = "http://www.foneparking.com.br/api/api.php/users/?csrf=".$output."/"; // where you want to post data
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_POST, true);  // tell curl you want to post something
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=Joao&email=some@emailoop.com"); // define what you want to post
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // return the output in string format
$output2 = curl_exec ($ch); // execute


curl_close ($ch); // close curl handle

echo $url; // show output

var_dump($output2); // show output


?>
</pre>

**Comment by fvdias** [comment]
Got it to work. Figured out I was calling the COOKIEJAR and never the COOKIEFILE.

Thanks a lot. 

SOLVED!

**Comment by mevdschee** [comment]
You are welcome, glad it worked. Enjoy!
