### ISSUE TITLE
App fails to recognize token that  is returned

### ISSUE THREAD

**Issue by benhbell** [mevdschee/php-api-auth#8]
Hi there!

I'm running ubuntu 16.06 here and a mysql database. 

If I run the phpcrud api program without this auth stuff installed, I can get results by get method to /api.php

I then paste the the code from this repo in the /api.php file into the phpcrud /api file right above the the $api = new PHP_CRUD_API and uncomment the top half.

I change the 'secret' = 'testingtoken123'

I then visit /login_token.htmlI provide the username and password set as default in auth.php (username, password)

This sends me to login_token.php with a token. Clicking the OK button sends me back to the API page, but the page is blank. 

If I debug the code, shows me that it is failing to recognize a session.
If I use that token and go to /api.php?csrf=eyJ0eXAicOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0ODMyMjMyMzgsImV4cCI6MTQ4MzIyMzI2OH0.3Z1Z9CZMJwRc8HR03iN5TrczXrMrUO8q6_awuM5cf0s

I still get a blank page.
Debugging the code, i get to line 164 which tells me that I should get a success.
I also see my token getting evaluated on 113.

Any help here would be appreciated. I would assume the outofthebox examples should work with a default installation. 

Thanks!

**Comment by mevdschee** [comment]
>but the page is blank.

That is not expected, it should show swagger output.

>/api.php?csrf=

That holds the csrf token and not the JWT token, so what you are doing is wrong (crsf token is numeric)

Maybe you uncommented both authentication sections?

Maybe you did not uncomment the API configuration holding the '$api->executeCommand();' call?

**Comment by benhbell** [comment]
Hey Mevdschee, thanks for the assistance

I retried it by going to login_token.html and entering "username" and "password" into the fields, then hitting OK. When I debug the code, I see it generate a csrf token=3386954277485100800 

I see no change in behavior if I use that numeric token in the query.

here is the code as I have it in api.php

```
// uncomment the lines below when running in stand-alone mode:

// for token+session based authentication (see "login_token.html" + "login_token.php"):

 require 'auth.php';
 $auth = new PHP_API_AUTH(array(
 	'secret'=>'testingtoken123',
 ));
 if ($auth->executeCommand()) exit(0);
 if (empty($_SESSION['user']) || $_GET['csrf']!=$_SESSION['csrf']) {
      header('HTTP/1.0 401 Unauthorized');
      exit(0);
 }

// for form+session based authentication (see "login.html"):

// require 'auth.php';
// $auth = new PHP_API_AUTH(array(
// 	'authenticator'=>function($user,$pass){ if ($user=='admin' && $pass=='admin') $_SESSION['user']=$user; }
// ));
// if ($auth->executeCommand()) exit(0);
// if (empty($_SESSION['user']) || $_GET['csrf']!=$_SESSION['csrf']) {
//	header('HTTP/1.0 401 Unauthorized');
//	exit(0);
// }

// include your api code here:
//
// see: https://github.com/mevdschee/php-crud-api
//
// placeholder for testing:
 echo 'Access granted!';

 $api = new PHP_CRUD_API(array(
 	'dbengine'=>'MySQL',
 	'hostname'=>'127.0.0.1',
 	'username'=>'root',
 	'password'=>'password',
 	'database'=>'is_mvp_local',
 	'charset'=>'utf8'
 ));
 $api->executeCommand();
```

I do see that in auth.php my IDE is throwing some errors that some variables may not be defined inside the public function executeCommand()  function.
e.g. password, post, username, etc.

**Comment by mevdschee** [comment]
>but the page is blank.

Does the swagger output show when you comment out the authentication?

>I see no change in behavior if I use that numeric token in the query.

You need both the session cookie and the CSRF token.

>my IDE is throwing some errors

Can you post these?

**Comment by benhbell** [comment]
I think it is the first auth block that is not working. If I uncomment the second part, and then go to "login.html", enter admin and admin as the credentials, I am given a csrf. Using that csrf it all works!

It also works if I comment out the auth

I get the swagger output
``
Access granted!{"swagger":"2.0","info": [the rest of the settings]
``

I am trying to use postman to now get the CSRF
![selection_020](https://cloud.githubusercontent.com/assets/966644/21596187/d500be8e-d105-11e6-9aaf-437f50090575.png)

But I am having trouble getting it to return the CSRF for me


## Errors
Note that the second auth block works despite these errors so it might just be the IDE

on line 131 
``
$no_session = $authenticator && $secret; 
``
says taht $authenticator  and $secret are not defined

same for line 145
``
echo json_encode($this->generateToken($_SESSION,$time,$ttl,$algorithm,$secret));
``
ttl, algorithm and secret are not defined

and line 151
``
$claims = $this->getVerifiedClaims($input->$token,$time,$leeway,$ttl,$algorithm,$secret);
``
$time,$leeway,$ttl,$algorithm are not defined

**Comment by mevdschee** [comment]
You should have either the first or the second block commented out. Maybe that is the problem?

The file 'login_token.php' (together with 'login_token_html') is hosted somewhere and will provide you with a time limited JWT (when you submit username and password). The other file is your 'api.php' where you can login with the JWT and that will use a session cookie and CSRF for session management and security.

If you uncomment the second block you can directly login with username and password from 'login.html'. It will return you a session cookie and a CSRF that you both have to send along on your next request.

**Comment by benhbell** [comment]
I think it is the first auth block that is not working. If I uncomment the second part, and then go to "login.html", enter admin and admin as the credentials, I am given a csrf. Using that csrf it all works!

It also works if I comment out the auth

I get the swagger output
``
Access granted!{"swagger":"2.0","info": [the rest of the settings]
``

I am trying to use postman to now get the CSRF
![selection_020](https://cloud.githubusercontent.com/assets/966644/21596187/d500be8e-d105-11e6-9aaf-437f50090575.png)

But I am having trouble getting it to return the CSRF for me


## Errors
Note that the second auth block works despite these errors so it might just be the IDE

on line 131 
``
$no_session = $authenticator && $secret; 
``
says taht $authenticator  and $secret are not defined

same for line 145
``
echo json_encode($this->generateToken($_SESSION,$time,$ttl,$algorithm,$secret));
``
ttl, algorithm and secret are not defined

and line 151
``
$claims = $this->getVerifiedClaims($input->$token,$time,$leeway,$ttl,$algorithm,$secret);
``
$time,$leeway,$ttl,$algorithm are not defined

**Comment by benhbell** [comment]
Ok. I think we are getting so much closer. Really appreciate it.

If I leave the second auth block uncommented, I can login and get the csrf then use that in a browser and get it to work. 

If I go and then switch the comments so that it is the top. I cannot access anythings. 
1. Using Postman, I make a post request to login_token.php and provide a username and password as the input
![selection_021](https://cloud.githubusercontent.com/assets/966644/21597797/85d2a6c4-d11e-11e6-9f04-35102c28693a.png)
This returns to me a key
2. I then take that key and make a post to api.php/
I get a blank page
![selection_023](https://cloud.githubusercontent.com/assets/966644/21597816/ea9cd728-d11e-11e6-957a-a57f1c107886.png)

**Comment by benhbell** [comment]
I got it!

I replaced the first auth block code that was in my api.php file with what was in the clone of the php auth repo
`````
require 'auth.php';
 $auth = new PHP_API_AUTH(array(
 	'secret'=>'testingtoken123',
 ));
 if ($  auth->executeCommand()) exit(0);
 if (empty($_SESSION['user']) || $_GET['csrf']!=$_SESSION['csrf']) {
      header('HTTP/1.0 401 Unauthorized');
      exit(0);
 }
`````
there was an extra hidden space in the execute command.

````
require 'auth.php';
 $auth = new PHP_API_AUTH(array(
 	'secret'=>'someVeryLongPassPhraseChangeMe',
 ));
 if ($auth->executeCommand()) exit(0);
 if (empty($_SESSION['user']) || $_GET['csrf']!=$_SESSION['csrf']) {
      header('HTTP/1.0 401 Unauthorized');
      exit(0);
 }
````

Doing so, I followed the steps again and this time I got the output!

Thank you so much.

**Comment by mevdschee** [comment]
I'm glad you figured it out, enjoy the software!

NB: If there is any room for improvement, please let me know.
