### ISSUE TITLE
I have a issue in php 5.6.27

### ISSUE THREAD

**Issue by Surojd** [mevdschee/php-api-auth#9]
[03-Jan-2017 01:10:35] PHP Warning:  Unexpected character in input:  '\' (ASCII=92) state=1 in /home4/nepalblo/public_html/API.php on line 192
[03-Jan-2017 01:10:35] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home4/nepalblo/public_html/API.php on line 205

**Comment by mevdschee** [comment]
Thank you for reaching out. Please post the contents of those lines, including the preceding line.

**Comment by Surojd** [comment]
if (!$success) {
            throw new \Exception('Connect failed. ' . mysqli_connect_error());//this is the line 192
        }

-----------------------------------------------------------------------------------------------------------------
public function query($sql, $params = array()) {
        $db = $this->db;
        $sql = preg_replace_callback('/\!|\?/', function ($matches) use (&$db, &$params) {//this is the line 205
            $param = array_shift($params);

**Comment by mevdschee** [comment]
Both warnings are from a PHP version older than 5.3, are you sure you run PHP 5.6 and not MYSQL 5.6?

```
<?php
die(phpversion());
```

Put the above line in a PHP file on your server and request it using the browser, you can post the output.

**Comment by Surojd** [comment]
OK and thanks,,
